services:
  db:
    image: postgres
    container_name: 1j1s-cms_db_1
    restart: always
    environment:
      POSTGRES_DB: 1j1s-cms
      POSTGRES_USER: admin-1j1s-cms
      POSTGRES_PASSWORD: 1front1cms
    ports:
      - 5432:5432
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.27.2
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - meilisearch
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped

networks:
  meilisearch:
    driver: bridge
